// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UsandooSRSTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void usandooSRS() {
    // Test name: Usando o SRS
    // Step # | name | target | value
    // 1 | open | /Sistema_Reserva_de_Salas/index.jsf | 
    driver.get("https://srs.ufersa.edu.br/Sistema_Reserva_de_Salas/index.jsf");
    // 2 | setWindowSize | 1022x718 | 
    driver.manage().window().setSize(new Dimension(1022, 718));
    // 3 | type | id=j_idt13:login | alyssonmilanez
    driver.findElement(By.id("j_idt13:login")).sendKeys("alyssonmilanez");
    // 4 | type | id=j_idt13:senha | 123
    driver.findElement(By.id("j_idt13:senha")).sendKeys("123");
    // 5 | click | css=.ui-button-text | 
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    // 6 | click | css=.ui-menuitem-active:nth-child(1) .ui-menuitem-text | 
    driver.findElement(By.cssSelector(".ui-menuitem-active:nth-child(1) .ui-menuitem-text")).click();
    // 7 | click | id=formReserva:data_input | 
    driver.findElement(By.id("formReserva:data_input")).click();
    // 8 | click | linkText=12 | 
    driver.findElement(By.linkText("12")).click();
    // 9 | click | id=formReserva:horaInicio_input | 
    driver.findElement(By.id("formReserva:horaInicio_input")).click();
    // 10 | type | id=formReserva:horaInicio_input | 15:00
    driver.findElement(By.id("formReserva:horaInicio_input")).sendKeys("15:00");
    // 11 | click | css=.ui-card-body | 
    driver.findElement(By.cssSelector(".ui-card-body")).click();
    // 12 | click | id=formReserva:horaFim_input | 
    driver.findElement(By.id("formReserva:horaFim_input")).click();
    // 13 | type | id=formReserva:horaFim_input | 16:00
    driver.findElement(By.id("formReserva:horaFim_input")).sendKeys("16:00");
    // 14 | click | css=.ui-card-body | 
    driver.findElement(By.cssSelector(".ui-card-body")).click();
    // 15 | click | id=formReserva:finalidade | 
    driver.findElement(By.id("formReserva:finalidade")).click();
    // 16 | type | id=formReserva:finalidade | Teste....
    driver.findElement(By.id("formReserva:finalidade")).sendKeys("Teste....");
    // 17 | click | css=#formReserva\3Aj_idt54 > .ui-button-text | 
    driver.findElement(By.cssSelector("#formReserva\\3Aj_idt54 > .ui-button-text")).click();
    // 18 | click | linkText=Sair | 
    driver.findElement(By.linkText("Sair")).click();
    // 19 | type | id=j_idt13:login | alyssonmilanez
    driver.findElement(By.id("j_idt13:login")).sendKeys("alyssonmilanez");
    // 20 | type | id=j_idt13:senha | wAsF2rn
    driver.findElement(By.id("j_idt13:senha")).sendKeys("wAsF2rn");
  }
}
