// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AcessandoGoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void acessandoGoogle() {
    driver.get("https://www.globo.com/");
    driver.manage().window().setSize(new Dimension(1860, 1053));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.cssSelector("center:nth-child(1) > .RNmpXc")).click();
    driver.findElement(By.cssSelector(".on img")).click();
    driver.findElement(By.cssSelector(".history-card:nth-child(15) img")).click();
    driver.findElement(By.cssSelector(".history-card:nth-child(16) img")).click();
    driver.findElement(By.id("searchinput")).click();
    driver.findElement(By.id("searchinput")).sendKeys("aloha");
    driver.findElement(By.id("searchbtn")).click();
  }
}
