// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Acessando-iFood', async function() {
    await driver.get("https://www.globo.com/")
    await driver.manage().window().setRect({ width: 1860, height: 1053 })
    await driver.findElement(By.css(".landing-v2-address-search__input")).click()
    await driver.findElement(By.css(".landing-v2-address-search__input")).sendKeys("jantar")
    await driver.findElement(By.css(".landing-v2-address-search__input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("li:nth-child(1) .btn-address--full-size")).click()
    await driver.findElement(By.css(".address-maps__submit > .btn__label")).click()
    {
      const element = await driver.findElement(By.css(".btn:nth-child(2) > .btn__label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn--full-width")).click()
    {
      const element = await driver.findElement(By.css(".carousel__slide:nth-child(6) .round-image__figure"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".carousel__slide:nth-child(4) .round-image__figure")).click()
  })
  it('Acessando-Google', async function() {
    await driver.get("https://www.globo.com/")
    await driver.manage().window().setRect({ width: 1860, height: 1053 })
    await driver.findElement(By.name("q")).click()
    await driver.findElement(By.css("center:nth-child(1) > .RNmpXc")).click()
    await driver.findElement(By.css(".on img")).click()
    await driver.findElement(By.css(".history-card:nth-child(15) img")).click()
    await driver.findElement(By.css(".history-card:nth-child(16) img")).click()
    await driver.findElement(By.id("searchinput")).click()
    await driver.findElement(By.id("searchinput")).sendKeys("aloha")
    await driver.findElement(By.id("searchbtn")).click()
  })
  it('Acesso-Globo', async function() {
    await driver.get("https://www.globo.com/")
    await driver.manage().window().setRect({ width: 1018, height: 854 })
    await driver.findElement(By.css(".headline__container .post__title")).click()
    await driver.executeScript("window.scrollTo(0,935)")
    await driver.executeScript("window.scrollTo(0,2606)")
    await driver.executeScript("window.scrollTo(0,3326)")
    await driver.switchTo().frame(0)
    await driver.switchTo().frame(0)
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.switchTo().defaultContent()
    await driver.switchTo().defaultContent()
    await driver.executeScript("window.scrollTo(0,4267)")
    await driver.executeScript("window.scrollTo(0,7064)")
    await driver.executeScript("window.scrollTo(0,9226)")
    await driver.executeScript("window.scrollTo(0,10468)")
    await driver.executeScript("window.scrollTo(0,12098)")
  })
})
