# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAcessandoGoogle():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_acessandoGoogle(self):
    self.driver.get("https://www.globo.com/")
    self.driver.set_window_size(1860, 1053)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .RNmpXc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".on img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".history-card:nth-child(15) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".history-card:nth-child(16) img").click()
    self.driver.find_element(By.ID, "searchinput").click()
    self.driver.find_element(By.ID, "searchinput").send_keys("aloha")
    self.driver.find_element(By.ID, "searchbtn").click()
  
