# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_acessandoiFood(self):
    self.driver.get("https://www.globo.com/")
    self.driver.set_window_size(1860, 1053)
    self.driver.find_element(By.CSS_SELECTOR, ".landing-v2-address-search__input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".landing-v2-address-search__input").send_keys("jantar")
    self.driver.find_element(By.CSS_SELECTOR, ".landing-v2-address-search__input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .btn-address--full-size").click()
    self.driver.find_element(By.CSS_SELECTOR, ".address-maps__submit > .btn__label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2) > .btn__label")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn--full-width").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__slide:nth-child(6) .round-image__figure")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel__slide:nth-child(4) .round-image__figure").click()
  
  def test_acessandoGoogle(self):
    self.driver.get("https://www.globo.com/")
    self.driver.set_window_size(1860, 1053)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .RNmpXc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".on img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".history-card:nth-child(15) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".history-card:nth-child(16) img").click()
    self.driver.find_element(By.ID, "searchinput").click()
    self.driver.find_element(By.ID, "searchinput").send_keys("aloha")
    self.driver.find_element(By.ID, "searchbtn").click()
  
  def test_acessoGlobo(self):
    self.driver.get("https://www.globo.com/")
    self.driver.set_window_size(1018, 854)
    self.driver.find_element(By.CSS_SELECTOR, ".headline__container .post__title").click()
    self.driver.execute_script("window.scrollTo(0,935)")
    self.driver.execute_script("window.scrollTo(0,2606)")
    self.driver.execute_script("window.scrollTo(0,3326)")
    self.driver.switch_to.frame(0)
    self.driver.switch_to.frame(0)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.switch_to.default_content()
    self.driver.switch_to.default_content()
    self.driver.execute_script("window.scrollTo(0,4267)")
    self.driver.execute_script("window.scrollTo(0,7064)")
    self.driver.execute_script("window.scrollTo(0,9226)")
    self.driver.execute_script("window.scrollTo(0,10468)")
    self.driver.execute_script("window.scrollTo(0,12098)")
  
